--문제 1.

SELECT first_name || ' ' || LAST_NAME AS "이름",
       SALARY AS "월급",
       PHONE_NUMBER AS "전화번호"
  FROM EMPLOYEES;

--문제2.

  SELECT JOB_TITLE, MAX_SALARY
    FROM JOBS
ORDER BY MAX_SALARY DESC;

--문제3.

SELECT COUNT (*)
  FROM employees
 WHERE MANAGER_ID IS NULL;

--문제4.

  SELECT job_id, salary
    FROM employees
ORDER BY salary DESC;

SELECT *
  FROM jobs
 WHERE job_id = 'AD_pres';

--문제5.

SELECT COUNT (DISTINCT DEPARTMENT_ID) FROM EMPLOYEES;

--문제6.

  SELECT DEPARTMENT_NAME
    FROM DEPARTMENTS
ORDER BY LENGTH (DEPARTMENT_NAME) ASC;

--SELECT department_name, UPPER (department_name) FROM DEPARTMENTS;

--문제7. *****************

SELECT COUNT (*)
  FROM DEPARTMENTS
 WHERE MANAGER_ID IS NULL;

--문제8.

  SELECT UPPER (COUNTRY_NAME)
    FROM COUNTRIES
   WHERE REGION_ID IS NOT NULL
ORDER BY COUNTRY_NAME ASC;

--문제9.

  SELECT REGION_NAME
    FROM REGIONS
ORDER BY LENGTH (REGION_NAME) ASC;

--문제10

  SELECT DISTINCT (LOWER (CITY))
    FROM DEPARTMENTS, LOCATIONS
   WHERE LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
ORDER BY (LOWER (CITY)) ASC;