--Date

SELECT EMPLOYEE_id, hire_date FROM EMPLOYEES;

SELECT VALUE
  FROM nls_session_parameters
 WHERE parameter = 'NLS_DATE_FORMAT';

SELECT ADD_MONTHS ('15/10/05', 2) FROM DUAL;

SELECT LAST_DAY (SYSDATE) FROM DUAL;

SELECT MONTHS_BETWEEN (ADD_MONTHS (SYSDATE, 2), SYSDATE) FROM DUAL;

SELECT EMPLOYEE_ID, JOB_ID, ROUND (MONTHS_BETWEEN (END_DATE, START_DATE))
  FROM JOB_HISTORY;

--SELECT NEXT_DAY('01-SEP-95','FRIDAY')FROM DUAL;
--1-> SUN ,7 -> SAT
SELECT NEXT_DAY ('16/10/05', 7) FROM DUAL;